# Generated by Django 5.2 on 2026-06-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("jira", "Jira"),
                            ("slack", "Slack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("url", models.URLField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "provider", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("jira", "Jira"),
                            ("slack", "Slack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=512)),
                ("url", models.URLField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "provider", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="RepositoryWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("commit_count", models.IntegerField(default=0)),
                ("issue_count", models.IntegerField(default=0)),
                ("pr_count", models.IntegerField(default=0)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="orgdata.contributor",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="orgdata.repository",
                    ),
                ),
            ],
            options={
                "unique_together": {("repository", "contributor")},
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True)),
                ("title", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("is_pull_request", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="orgdata.repositorywork",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=128)),
                ("url", models.URLField(blank=True)),
                ("message", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("additions", models.IntegerField(default=0)),
                ("deletions", models.IntegerField(default=0)),
                ("authored_at", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="orgdata.repositorywork",
                    ),
                ),
            ],
        ),
    ]
